version: "3"

services:
  backend:
    build:
      context: ./backend
    networks:
      - codesentinel
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    networks:
      - codesentinel
    ports:
      - "3000:80"

networks:
  codesentinel:
    driver: bridge
